CREATE TABLE notification (
	idx INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	section VARCHAR(15) NOT NULL, 
	sort VARCHAR(15) NOT NULL, 
	superIdx INT NOT NULL, 
	reIdx INT NOT NULL, 
	toMid VARCHAR(10) NOT NULL,
	fromMid VARCHAR(10) NOT NULL,
	checked BOOLEAN NOT NULL DEFAULT FALSE,
	actDate DATETIME NOT NULL DEFAULT NOW()
)

DROP TABLE notification 

CREATE TABLE message (
	idx INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	toMid VARCHAR(10) NOT NULL,
	fromMid VARCHAR(10) NOT NULL,
	subject text NOT NULL,
	sendDate DATETIME NOT NULL DEFAULT NOW(),
	checked BOOLEAN NOT NULL DEFAULT 0
)

DROP TABLE message 