CREATE TABLE member2 (
	idx INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	mid VARCHAR(10) NOT NULL UNIQUE KEY, 
	pwd VARCHAR(100) NOT NULL, 
	firstName VARCHAR(20) NOT NULL, 
	lastName VARCHAR(20) NOT NULL, 
	region VARCHAR(30) NOT NULL, 
	birthday DATE NOT NULL,
	email VARCHAR(30) NOT NULL, 
	tel VARCHAR(20) NOT NULL, 
	photo VARCHAR(1000) NOT NULL, 
	point INT NOT NULL DEFAULT 100, 
	levelB INT NOT NULL DEFAULT 0,
	levelC INT NOT NULL DEFAULT 0, 
	levelM INT NOT NULL DEFAULT 0, 
	signUpDate DATETIME NOT NULL DEFAULT NOW(),
	lastDate DATETIME NOT NULL DEFAULT NOW(),
	visitCnt INT NOT NULL DEFAULT 0, 
	visibility BOOLEAN NOT NULL DEFAULT TRUE,
	isActive BOOLEAN NOT NULL DEFAULT TRUE
)

INSERT INTO member2 VALUES (DEFAULT, 'admin', 'asdf!1', 'admin', '관리자', '', '2024-07-13', 'javask1121@gmail.com','', 'nopimg.jpg',default, 99,99,99, DEFAULT, DEFAULT,DEFAULT, DEFAULT, default )

DROP TABLE member2

CREATE TABLE memberBlock (
	idx INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	mid VARCHAR(10) NOT NULL, 
	toMid VARCHAR(10) NOT NULL,
	blockDate DATETIME NOT NULL DEFAULT NOW(),
	FOREIGN KEY (mid) REFERENCES member2 (mid),
	FOREIGN KEY (toMid) REFERENCES member2 (mid)
);

DROP TABLE memberBlock